In [1]:
#%%
from pathlib import Path
import streamlit as st

from lib import myplots
from lib import sthelper


# Filepath constants for input data and markdown
INPUT_DIR = Path.cwd()  / "input"
MD_DIR = Path.cwd() / "markdown"

# Base year for real value calculations
BASE_YEAR = 2024

# Webpage set up

# Create and plot time-series chart on the page
c, df= myplots.time_series(INPUT_DIR, BASE_YEAR)

2024-09-27 06:44:53.349 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2024-09-27 06:44:53.513 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2024-09-27 06:44:53.610
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/coosy/Documents/coding/python/venvs/stipdends2/lib/python3.10/site-packages/ipykernel_launcher.py [ARGUMENTS]
2024-09-27 06:44:53.611 No runtime found, using MemoryCacheStorageManager
2024-09-27 06:44:53.615 No runtime found, using MemoryCacheStorageManager

In [2]:
df

         year income_type        income midpoint_datetime
0  2012-01-01         NLW  13010.307500        2012-04-01
1  2013-01-01         NLW  13537.819552        2013-04-01
2  2014-01-01         NLW  14038.817269        2014-04-01
3  2015-01-01         NLW  14358.292000        2015-04-01
4  2016-01-01         NLW  15273.140594        2016-04-01
5  2017-01-01         NLW  15539.932432        2017-04-01
6  2018-01-01         NLW  15824.455094        2018-04-01
7  2019-01-01         NLW  16359.583302        2019-04-01
8  2020-01-01         NLW  17087.040955        2020-04-01
9  2021-01-01         NLW  16989.445161        2021-04-01
10 2022-01-01         NLW  16670.239004        2022-04-01
11 2023-01-01         NLW  17004.044790        2023-04-01
12 2024-01-01         NLW  18092.400000        2024-04-01
13 2012-01-01         RLW  15708.912500        2013-05-01
14 2013-01-01         RLW  16343.468432        2014-05-01
15 2014-01-01         RLW  16825.672691        2015-05-01
16 2015-01-01         RLW  17545.216000        2016-05-01
17 2016-01-01         RLW  17817.794059        2017-05-01
18 2017-01-01         RLW  18020.723938        2018-05-01
19 2018-01-01         RLW  18093.901887        2019-05-01
20 2019-01-01         RLW  18438.551020        2020-05-01
21 2020-01-01         RLW  18559.715335        2021-05-01
22 2021-01-01         RLW  18813.387097        2022-05-01
23 2022-01-01         RLW  19059.045643        2023-05-01
24 2023-01-01         RLW  19530.177294        2024-05-01
25 2024-01-01         RLW           NaN        2025-05-01
26 2012-01-01     Stipend  18657.937500        2012-08-01
27 2013-01-01     Stipend  18503.002037        2013-08-01
28 2014-01-01     Stipend  18344.813253        2014-08-01
29 2015-01-01     Stipend  18527.126000        2015-08-01
30 2016-01-01     Stipend  18655.572277        2016-08-01
31 2017-01-01     Stipend  18514.337838        2017-08-01
32 2018-01-01     Stipend  18373.666038        2018-08-01
33 2019-01-01     Stipend  18350.521336        2019-08-01
34 2020-01-01     Stipend  18499.201102        2020-08-01
35 2021-01-01     Stipend  18434.284946        2021-08-01
36 2022-01-01     Stipend  17568.229046        2022-08-01
37 2023-01-01     Stipend  18107.639191        2023-08-01
38 2024-01-01     Stipend  19237.000000        2024-08-01
39 2012-01-01    Graduate           NaN        2012-01-01
40 2013-01-01    Graduate           NaN        2013-01-01
41 2014-01-01    Graduate           NaN        2014-01-01
42 2015-01-01    Graduate           NaN        2015-01-01
43 2016-01-01    Graduate           NaN        2016-01-01
44 2017-01-01    Graduate           NaN        2017-01-01
45 2018-01-01    Graduate           NaN        2018-01-01
46 2019-01-01    Graduate           NaN        2019-01-01
47 2020-01-01    Graduate           NaN        2020-01-01
48 2021-01-01    Graduate           NaN        2021-01-01
49 2022-01-01    Graduate           NaN        2022-01-01
50 2023-01-01    Graduate           NaN        2023-01-01
51 2024-01-01    Graduate           NaN        2024-01-01

In [4]:
c

alt.Chart(...)